### ISSUE TITLE
Missing set options from code.sh

### ISSUE THREAD

**Issue by jethror1** [eastgenomics/eggd_MetricsOutput_edit#2]
Example here: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/4e5648560e0b240186884c1dbad090de9caa5641/src/code.sh#L3

Manual for GNU `set` explaining the options: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html

**Comment by Arun-bioinformatics** [comment]
Thank you! I have addressed this on the following PR https://github.com/eastgenomics/eggd_MetricsOutput_editor/pull/3
